name: EZE AI Secretary Daily

# updated
on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  run-eze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run EZE
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: |
          python main.py
